# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 05 Mar 2016 05:42:03 +0000
*	@ALL	1
*	@user	16
blog:ease:home	ease	2
blog:ease:home	@ALL	0
blog:ggw:home	格格巫	2
blog:ggw:home	@ALL	0
