<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ease
 * Date: Tue, 02 Aug 2016 17:59:59 +0800
 */

$conf['title'] = '有识';
$conf['lang'] = 'zh';
$conf['tagline'] = '追寻一切真知卓见 欢迎加入有识';
$conf['license'] = '0';
$conf['dformat'] = '%H:%M - %m月%d日';
$conf['signature'] = '<wrap lo right>//[[@MAIL@|@NAME@]] @DATE@//</wrap>';
$conf['useheading'] = '1';
$conf['hidepages'] = 'sidebar|home|index';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['blog']['sortkey'] = 'mdate';
$conf['plugin']['blog']['excluded_pages'] = '!^(blog:\\d{4}(:\\d{2})?|.*?index|.*?关于博主|.*?sidebar|.*?\\d{4})$!';
$conf['plugin']['blog']['showhistogram'] = 0;

// end auto-generated content
