<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ease
 * Date: Fri, 15 Jul 2016 18:53:59 +0800
 */

$conf['title'] = '由是';
$conf['lang'] = 'zh';
$conf['tagline'] = 'tagline';
$conf['license'] = '0';
$conf['dformat'] = '%H:%M - %m月%d日';
$conf['signature'] = '<wrap lo right>//[[@MAIL@|@NAME@]] @DATE@//</wrap>';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['blog']['sortkey'] = 'mdate';
$conf['plugin']['blog']['excluded_pages'] = '!^(blog:\\d{4}(:\\d{2})?|.*?index|.*?sidebar|.*?\\d{4})$!';
$conf['plugin']['blog']['showhistogram'] = 0;

// end auto-generated content
