<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ease
 * Date: Fri, 22 Apr 2016 16:36:15 +0800
 */

$conf['title'] = '由是';
$conf['lang'] = 'zh';
$conf['tagline'] = 'tagline';
$conf['license'] = '0';
$conf['dformat'] = '%H:%M - %m月%d日';
$conf['signature'] = '<wrap lo right>//[[@MAIL@|@NAME@]] @DATE@//</wrap>';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
