<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ease
 * Date: Wed, 29 Aug 2018 12:01:41 +0800
 */

$conf['title'] = '有识';
$conf['lang'] = 'zh';
$conf['tagline'] = '追寻一切真知灼见 欢迎加入有识';
$conf['license'] = '0';
$conf['savedir'] = '../dokuwiki_data';
$conf['dformat'] = '%H:%M - %m月%d日';
$conf['signature'] = '<wrap lo right>//[[@MAIL@|@NAME@]] @DATE@//</wrap>';
$conf['useheading'] = '1';
$conf['hidepages'] = 'sidebar|home|index|.*?pri';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'index,register';
$conf['auth_security_timeout'] = 927;
$conf['rss_linkto'] = 'current';
$conf['rss_show_summary'] = 0;
$conf['userewrite'] = '1';
$conf['plugin']['blog']['sortkey'] = 'mdate';
$conf['plugin']['blog']['excluded_pages'] = '!^(blog:\\d{4}(:\\d{2})?|.*?index|.*?month|.*?关于博主|.*?sidebar|.*?\\d{4})$!|.*?pri';
$conf['plugin']['blog']['showhistogram'] = 0;

// end auto-generated content
